# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

Rails::Application.load_tasks

namespace :test_unit do
  desc "runs the test::unit based tests in webrat mode"
  task :rails do
    ENV['WEBRAT_INTEGRATION_MODE'] = 'rails'
    Rake::Task['test:integration'].execute
  end

  desc "runs the test::unit based tests in selenium mode"
  task :selenium do
    ENV['WEBRAT_INTEGRATION_MODE'] = 'selenium'
    Rake::Task['test:integration'].execute
  end

  desc "run both selenium and rails mode Test::Unit suites"
  task :all => [:rails, :selenium]
end